config/routes.rb
Rails.application.routes.draw do

  #リダイレクト先変更のため、それぞれ指定したコントローラを経由するように指示
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "home/about" => "home#about"

#indexは「/コントローラ名」をルーティングしてくれるよ！
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :edit, :update, :create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

#books　が1対NのNにあたるので複数形
  has_many :books, dependent: :destroy

#viewでイメージを表示するために必須
  attachment :profile_image

#名前が空欄でないか,長さは十分かバリデーション　ちなみに  validates :カラム名, カラム名... ,ヘルパーという書き方も可能
  validates :name, length: { minimum: 2, maximum: 20 }, presence: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  #アカウント登録後のリダイレクト先
def after_sign_up_path_for(resource)
  user_path(current_user.id)
end

  #アカウント編集後のリダイレクト先
def after_update_path_for(resource)
  user_path(current_user.id)
end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  #ログイン後のリダイレクト先
def after_sign_in_path_for(resource)
  user_path(current_user.id)
end
  #ログアウト後のリダイレクト先
def after_sign_out_path_for(resource)
  root_path
end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #ログイン中のユーザーのみが指定アクションをできるようにする
  before_action :authenticate_user!, only: [:edit, :index, :show]
  def show
  	@user = User.find(params[:id])
  	@books = @user.books #user.idとbook.user_idが紐づいていて。現在のuser_idからデータが全て持ってこれる
  	@book_new = Book.new
  end

  def index
  	@users = User.all
  	@user = User.find(current_user.id)
  	@books_all = Book.all
   	@book_new = Book.new
  	@book_new.user_id = current_user.id
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
  	else
  	  render :edit
  	end
  end
  private
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end
  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<!--　ブックの新規投稿のエラー文表示コード 部分テンプレートに入れるとすごくめんどくさい -->
<!--< if book.errors.any? %>
  <div id="error_explanation">
    <h2><= book.errors.count %>件のエラーが発生しました。</h2>
    <ul>
    < book.errors.full_messages.each do |message| %>
    <li><= message %></li>
    < end %>
    </ul>
  </div>
< end %>-->
<div>
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, size:"60x60", format: 'jpeg', fallback: "no_image.jpg" %>
  <table width="80%" class="table">
    <thead>
  	  <tr>
  	    <th><b>name</b></th>
  		<th><%= user.name %></th>
  	  </tr>
  	  <tr>
  	  	<th><b>introduction</b></th>
  	  	<th><%= user.introduction %></th>
  	</thead>
  	<tbody>
  	</tbody>
  </table>

      <p><%= link_to "Edit", edit_user_path(user), class: "btn btn-lg btn-block btn-base-1 mt-20 btn-default " %></p>

</div>
<!--　ブックの新規投稿用コード -->
<div>
  <h2>New book</h2>
  <%= form_for(book_new) do |f| %>
    <div class="form-group has-icon">
      <label for="inputEmail">Title</label>
      <%= f.text_field :title, autofocus: true, class:"form-control" %>
      <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>
    <div class="form-group has-icon">
      <label for="inputEmail">Opinion</label>
      <%= f.text_area :body, autofocus: true, class:"form-control" %>
      <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>
    <%= f.submit "Create Book", class: "btn btn-lg btn-block btn-base-1 mt-20 btn-primary" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">
          <section class="slice slice-lg sct-color-1">
              <div class="container">
                  <div class="row">
                      <div class="col-md-4 col-md-offset-4">
                          <div class="form-user style-1 rounded has-shadow-1">
                            <div class="form-header text-center">
                                <h2 class="form-header-title">User Info</h2>
                            </div>
                            <div class="form-body">

                              <h2>User info</h2>
                              <%= form_for(@user) do |f| %>
                                <!-- バリデーションチェックを通らなかった時のエラー文表示コード -->
                                <% if @user.errors.any? %>
                                  <div id="error_explanation">
                                    <h2><%= @user.errors.count %>件のerrorが発生しました。</h2>
                                    <ul>
                                    <% @user.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                    <% end %>
                                    </ul>
                                  </div>
                                <% end %>

                                <div class="form-group has-icon">
                                  <div class="user-edit-image">
                                    <%= attachment_image_tag @user, :profile_image, size:"60x60", fallback: "no_image.jpg"%>
                                  </div>
                                  <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
                                  <%= f.attachment_field :profile_image, class: "user-edit-form" %>
                                </div>
                                <div class="form-group has-icon">
                                  <label for="inputEmail">Name</label>
                                  <%= f.text_field :name, autofocus: true, class:"form-control" %>
                                  <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                                </div>
                                <div class="form-group has-icon">
                                  <label for="inputEmail">Introduction</label>
                                  <%= f.text_area :introduction, autofocus: true, class:"form-control" %>
                                  <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                                </div>
                                <%= f.submit "Update User", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                              <% end %>

                            </div>
                          </div>
                      </div>
                  </div>
              </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <!-- ローカル変数にインスタンス定数を代入 -->
      <%= render 'users/list', user: @user, book_new: @book_new %>
    </div>
    <div class="col-xs-9">
      <h2>Users</h2>
      <table width="80%" class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <!-- 展開用コード-->
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <div class="user-edit-image">
                <%= link_to user_path(user.id) do %>
                <%= attachment_image_tag user, :profile_image, size:"30x30", fallback: "no_image.jpg"%>
                <% end %>
              </div>
            </td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- :noticeの値が代入される=signin、updateされた。ってことはif文で書く必要なくね？とも考えたが一応。こうした-->
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <!-- ローカル変数にインスタンス定数を代入 -->
      <%= render 'users/list', user: @user, book_new: @book_new %>
    </div>
    <div class="col-xs-9">
      <h2>Books</h2>
      <table width="80%" class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <!-- 自分のブックのみ展開するコード-->
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <div class="user-edit-image">
                <%= link_to user_path(book.user_id) do %>
                <%= attachment_image_tag @user, :profile_image, size:"30x30", fallback: "no_image.jpg"%>
                <% end %>
              </div>
            </td>
            <td><%= link_to book.title,book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>