config/routes.rb
Rails.application.routes.draw do

  #リダイレクト先変更のため、それぞれ指定したコントローラを経由するように指示
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get "home/about" => "home#about"

#indexは「/コントローラ名」をルーティングしてくれるよ！
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :edit, :update, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="body">
    <header>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container relative">

          <ul class="nav navbar-nav navbar-left" >
            <li>
              <font color="white"><h4>Bookers</h4></font>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right" >
            <% if user_signed_in? %>
              <li class="">
                <%= link_to 'Home', user_path(current_user.id) %>
              </li>
              <li class="">
                <%= link_to 'Users', users_path %>
              </li>
              <li class="">
                <%= link_to 'Books', books_path %>
              </li>
              <li class="">
                <%= link_to "logout", destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li class="">
                <%= link_to "Home", root_path %>
              </li>
              <li class="">
                <%= link_to "About", home_about_path %>
              </li>
              <li class="">
                <%= link_to "Sign up", new_user_registration_path %>
              </li>
              <li class="">
                <%= link_to "login", new_user_session_path %>
              </li>
            <% end %>
          </ul>

        </div>
      </nav>
    </header>

    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-10">
          </div>
          <div class="col-lg-2">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>